#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
  site_name: 'Desafio Marketplace'
  entities:
    Product:
      class: App\Entity\Product    
      # ...
      list:
        fields:
            - { property: 'name', type: 'string' }
            - { property: 'description', type: 'text' }
            - { property: 'price', type: 'string' }
            - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
      # ...
      show:
        fields:
              - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
      form:
        fields:
          - { property: 'name', type: 'text' }
          - { property: 'description', type: 'textarea' }
          - { property: 'price', type: 'number' }
          - { property: 'imageFile', type: 'vich_image' }