easy_admin:
  site_name: 'Desafio Marketplace'
  design:
    form_theme: 'vertical'
  entities:
    Product:
      class: App\Entity\Product    
      list:
        fields:
            - { property: 'name', type: 'string' }
            - { property: 'description', type: 'text' }
            - { property: 'price', type: 'string'}
            - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
      show:
        fields:
              - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
      form:
        fields:
          - { property: 'name', type: 'text' }
          - { property: 'description', type: 'textarea' }
          - { property: 'price', type: 'money', type_options: { currency: 'BRL' } }
          - { property: 'imageFile', type: 'vich_image' }

    User:
      class: App\Entity\User
      list:
        fields:
            - username
            - email
            - enabled
            - lastLogin
            - roles
      form:
          fields:
              - username
              - email
              - enabled
              - bankAccount
              - transferEnabled
              - { property: 'transferInterval', type: 'choice', type_options: { multiple: false, choices: { 'Diariamente': 'daily', 'Semanalmente': 'weekly', 'Mensalmente' : 'monthly' } } }
              - transferDay
              - automaticAnticipationEnabled
              - anticipatableVolumePercentage
              - { property: 'plainPassword', type: 'text', type_options: { required: false } }
              - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'Regular user': 'ROLE_USER', 'Administrator': 'ROLE_ADMIN' } } }

    BankAccount:
      class:  App\Entity\BankAccount
