fos_user:
    registration:
        confirmation:
            enabled: false
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: andre.mendesc@gmail.com
        sender_name: André Mendes
    resetting:
        email:
            from_email:
                address:        andre.mendesc@gmail.com
                sender_name:    André Mendes